name: "Dispatcharr"
slug: "dispatcharr"
description: "Dispatcharr IPTV management"
version: "1.0.0"

startup: services
boot: auto
init: false

ports:
  9191/tcp: 9191

arch:
  - aarch64
  - amd64

options:
  web_port: 9191
  log_level: INFO

schema:
  web_port: port
  log_level: list(DEBUG|INFO)?
